// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 15/5/2026, 07:06:54
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/cfvhc/OneDrive/Desktop/asytec-nuxt/asytec-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/cfvhc/OneDrive/Desktop/asytec-nuxt/asytec-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/cfvhc/OneDrive/Desktop/asytec-nuxt/asytec-nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/cfvhc/OneDrive/Desktop/asytec-nuxt/asytec-nuxt/plugins/**/*.{js,ts,mjs}","C:/Users/cfvhc/OneDrive/Desktop/asytec-nuxt/asytec-nuxt/composables/**/*.{js,ts,mjs}","C:/Users/cfvhc/OneDrive/Desktop/asytec-nuxt/asytec-nuxt/utils/**/*.{js,ts,mjs}","C:/Users/cfvhc/OneDrive/Desktop/asytec-nuxt/asytec-nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/cfvhc/OneDrive/Desktop/asytec-nuxt/asytec-nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/cfvhc/OneDrive/Desktop/asytec-nuxt/asytec-nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/cfvhc/OneDrive/Desktop/asytec-nuxt/asytec-nuxt/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;